name: Deploy to Azure

on:
  push:
    branches: [ main ]
    paths: 
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

env:
  REGISTRY_NAME: kevintestquotebotprodacr
  RESOURCE_GROUP: kevin-test-rg3
  WEB_APP_NAME: kevin-test-quote-bot-prod-webapp
  IMAGE_NAME: quote-agent-bot

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Container Registry
      run: az acr login --name ${{ env.REGISTRY_NAME }}

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 \
          -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest \
          --push .

    - name: Update Web App container
      run: |
        az webapp config container set \
          --name ${{ env.WEB_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --docker-custom-image-name ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Restart Web App
      run: |
        az webapp restart \
          --name ${{ env.WEB_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }}

    - name: Verify deployment
      run: |
        echo "Deployment completed successfully!"
        echo "Bot endpoint: https://${{ env.WEB_APP_NAME }}.azurewebsites.net/api/messages"
